import { Router } from "express";
import { list, getById, create, update, setPermissions, resetPassword } from "#controllers/admins.controller.js";
import { requireAdmin, requireSuperAdmin } from "#middlewares/adminAuth.js";
import { asyncHandler } from "@xprtlink/shared/middleware/asyncHandler.js";
const router = Router();
router.use(requireAdmin, requireSuperAdmin);
router.get("/", asyncHandler(list));
router.post("/", asyncHandler(create));
router.get("/:id", asyncHandler(getById));
router.patch("/:id", asyncHandler(update));
router.put("/:id/permissions", asyncHandler(setPermissions));
router.put("/:id/reset-password", asyncHandler(resetPassword));
export default router;
