import { Router } from "express";
import { list, getById, create, update, setPermissions } from "#controllers/admins.controller.js";
import { requireAdmin, requireSuperAdmin } from "#middlewares/adminAuth.js";
const router = Router();
router.use(requireAdmin, requireSuperAdmin);
router.get("/", list);
router.post("/", create);
router.get("/:id", getById);
router.patch("/:id", update);
router.put("/:id/permissions", setPermissions);
export default router;
