import { Router } from "express";
import { list, getById, refund } from "#controllers/payments.controller.js";
import { requireAdmin, requirePermission } from "#middlewares/adminAuth.js";
import { asyncHandler } from "@xprtlink/shared/middleware/asyncHandler.js";
const router = Router();
router.use(requireAdmin);
router.get("/", requirePermission("payments", "view"), asyncHandler(list));
router.get("/:id", requirePermission("payments", "view"), asyncHandler(getById));
router.post("/:id/refund", requirePermission("payments", "edit"), asyncHandler(refund));
export default router;
