import { Router } from "express";
import { list, getById, markPaid } from "#controllers/payouts.controller.js";
import { requireAdmin, requirePermission } from "#middlewares/adminAuth.js";
import { asyncHandler } from "@xprtlink/shared/middleware/asyncHandler.js";
const router = Router();
router.use(requireAdmin);
router.get("/", requirePermission("payouts", "view"), asyncHandler(list));
router.get("/:id", requirePermission("payouts", "view"), asyncHandler(getById));
router.patch("/:id/mark-paid", requirePermission("payouts", "edit"), asyncHandler(markPaid));
export default router;
