import { Router } from "express";
import { list, getById, hide, publish } from "#controllers/reviews.controller.js";
import { requireAdmin, requirePermission } from "#middlewares/adminAuth.js";
const router = Router();
router.use(requireAdmin);
router.get("/", requirePermission("reviews", "view"), list);
router.get("/:id", requirePermission("reviews", "view"), getById);
router.patch("/:id/hide", requirePermission("reviews", "edit"), hide);
router.patch("/:id/publish", requirePermission("reviews", "edit"), publish);
export default router;
