import { Router } from "express";
import { list, getById, hide, publish } from "#controllers/reviews.controller.js";
import { requireAdmin } from "#middlewares/adminAuth.js";
const router = Router();
router.use(requireAdmin);
router.get("/", list);
router.get("/:id", getById);
router.patch("/:id/hide", hide);
router.patch("/:id/publish", publish);
export default router;
